service: monetized-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      name: monetized-api-dynamodb
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: !GetAtt usersTable.Arn

functions:
  testGet:
    handler: endpoints/testGet.handler
    events:
      - http: GET /testGet
  testDynamo:
    handler: endpoints/testDynamo.handler
    events:
      - http: POST /testDynamo

  checkout:
    handler: endpoints/checkout.handler
    events:
      - http: POST /checkout
  stripeWebhooks:
    handler: endpoints/stripeWebhooks.handler
    events:
      - http: POST /webhook

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable-monetized-api
        AttributeDefinitions:
          - AttributeName: customerId
            AttributeType: S
          - AttributeName: apiKey
            AttributeType: S
        KeySchema:
          - AttributeName: customerId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ApiKey
            KeySchema:
              - AttributeName: apiKey
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true

plugins:
  - serverless-dynamodb-local
  - serverless-offline
