service: monetized-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  testGet:
    handler: endpoints/testGet.handler
    events:
      - http: GET /testGet
  checkout:
    handler: endpoints/checkout.handler
    events:
      - http: POST /checkout

plugins:
  - serverless-offline
